[package]
name = "gettis-r"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.28"
pixels = "0.13"
log = "0.4"
env_logger = "0.10"
rayon = "1.5"
image = "0.25"
nalgebra = "0.33.2"
gltf = "1.4.1"
rand = "0.8"
glam = "0.30.3"
